"""first

Revision ID: 9e02f54d74c8
Revises: 
Create Date: 2020-03-14 21:18:07.104800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e02f54d74c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_name', sa.String(length=64), nullable=True),
    sa.Column('hospital_address', sa.String(length=64), nullable=True),
    sa.Column('hospital_website', sa.String(length=64), nullable=True),
    sa.Column('hospital_contact_num', sa.Integer(), nullable=True),
    sa.Column('hospital_email', sa.String(length=64), nullable=True),
    sa.Column('hospital_user_name', sa.String(length=64), nullable=True),
    sa.Column('hospital_pw_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Hospitals_hospital_user_name'), 'Hospitals', ['hospital_user_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Hospitals_hospital_user_name'), table_name='Hospitals')
    op.drop_table('Hospitals')
    # ### end Alembic commands ###
