"""

Revision ID: d3111f43c173
Revises: 
Create Date: 2020-03-17 02:21:23.046171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3111f43c173'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_name', sa.String(length=64), nullable=True),
    sa.Column('hospital_address', sa.String(length=64), nullable=True),
    sa.Column('hospital_website', sa.String(length=64), nullable=True),
    sa.Column('hospital_contact_num', sa.Integer(), nullable=True),
    sa.Column('hospital_email', sa.String(length=64), nullable=True),
    sa.Column('hospital_user_name', sa.String(length=64), nullable=True),
    sa.Column('hospital_pw_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_hospital_user_name'), 'hospitals', ['hospital_user_name'], unique=True)
    op.create_table('hospitalinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('num_confirmed_covid', sa.Integer(), nullable=True),
    sa.Column('num_pui', sa.Integer(), nullable=True),
    sa.Column('request_supplies', sa.String(length=64), nullable=True),
    sa.Column('num_covid_kits', sa.Integer(), nullable=True),
    sa.Column('num_face_masks', sa.Integer(), nullable=True),
    sa.Column('num_surgical_gloves', sa.Integer(), nullable=True),
    sa.Column('num_alcohol', sa.Integer(), nullable=True),
    sa.Column('num_face_shield', sa.Integer(), nullable=True),
    sa.Column('num_hoods', sa.Integer(), nullable=True),
    sa.Column('num_shoe_covers', sa.Integer(), nullable=True),
    sa.Column('num_respirators', sa.Integer(), nullable=True),
    sa.Column('num_doctors_for_covid', sa.Integer(), nullable=True),
    sa.Column('num_nurses_for_covid', sa.Integer(), nullable=True),
    sa.Column('num_medstaff_for_covid', sa.Integer(), nullable=True),
    sa.Column('capacity_quarantine', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hospitalinfo')
    op.drop_index(op.f('ix_hospitals_hospital_user_name'), table_name='hospitals')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
